stages: 
  - gradle
  - deploy

gradle: 
  image: gradle:6.0.1-jdk8
  stage: gradle
  script: 
    - chmod + gradlew
    - ./gradlew publish
  only: 
    - master
  retry: 
    max: 2
    when: stuck_or_timeout_failure

trigger_downstream: 
  image: gradle:6.0.1-jdk8
  stage: deploy
  script: 
    # Walrus
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/14582879/trigger/pipeline
